
CREATE TABLE "MEMBER" (
	"MEM_NUM"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(12)	UNIQUE	NOT NULL,
	"MEM_AUTH"	NUMBER(1)	DEFAULT 2	NOT NULL,  /*0Å»Åð 1Á¤Áö 2ÀÏ¹Ý 9°ü¸®*/
	CONSTRAINT MEMBER_PK PRIMARY KEY (MEM_NUM)
);

CREATE TABLE "MEMBER_DETAIL" (
	"MEM_NUM"	NUMBER		 NULL,
	"MEM_PW"	VARCHAR2(20)		NOT NULL,
	"MEM_NAME"	VARCHAR2(30)		NOT NULL,
	"MEM_PHONE"	VARCHAR2(15)		NOT NULL,
	"MEM_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEM_PHOTO" VARCHAR2(150)	    NULL,
	"MEM_ZIPCODE"	VARCHAR2(5)		NULL,
	"MEM_ADDRESS1"	VARCHAR2(50)		NULL,
	"MEM_ADDRESS2"	VARCHAR2(50)		NULL,
	"MEM_REG"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEM_MODIFY"	DATE		NULL,
	CONSTRAINT MEMBER_DETAIL_PK PRIMARY KEY (MEM_NUM),
	CONSTRAINT MEMBER_DETAIL_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBER (MEM_NUM)
);
CREATE SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_DETAIL_SEQ;