CREATE TABLE "ORDER_MAIN" (
	"ORDER_MAIN_NUM"	NUMBER,							/* 주문번호 */
	"ORDER_MAIN_NAME"	VARCHAR2(600)		NOT NULL,	/* 상품이름 */
	"ORDER_MAIN_TOTAL"	NUMBER(7)		NOT NULL,		/* 총 가격 */
	"PAYMENT"	NUMBER(1)		NOT NULL,				/* 결제방식 */
	"STATUS"	NUMBER(1)	DEFAULT 1	NOT NULL,		/* 배송상태 */
	"RECEIVE_NAME"	VARCHAR2(30)		NOT NULL,		/* 수령자 이름 */
	"RECEIVE_ZIPCODE"	VARCHAR2(5)		NOT NULL,		/* 수령자 우편번호 */
	"RECEIVE_ADDRESS1"	VARCHAR2(90)		NOT NULL,	/* 수령자 주소 */
	"RECEIVE_ADDRESS2"	VARCHAR2(90)		NOT NULL,	/* 수령자 상세주소 */
	"RECEIVE_PHONE"	VARCHAR2(15)		NOT NULL,		/* 수령자 번호 */
	"NOTICE"	VARCHAR2(4000),							/* 메모 */
	"ORDER_MAIN_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,	/* 주문날짜 */
	"MODIFY_DATE" DATE,									/* 수정날짜 */
	"MEM_NUM"	NUMBER		NOT NULL,
	
	CONSTRAINT ORDER_MAIN_PK PRIMARY KEY (ORDER_MAIN_NUM),
	CONSTRAINT ORDER_MAIN_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBER_DETAIL (MEM_NUM)
);

CREATE TABLE "ORDER_DETAIL" (
	"ORDER_DETAIL_NUM"	NUMBER,						/* 상세주문번호 */
	"PRO_NUM"	NUMBER			NOT NULL,			/* 상품번호 */
	"PRO_NAME"	VARCHAR2(50)		NOT NULL,		/* 상품이름 */
	"PRO_PRICE"	NUMBER(8)		NOT NULL,			/* 상품가격 */
	"PRO_TOTAL"	NUMBER(8)		NOT NULL,			/* 상품 총 가격 */
	"ORDER_MAIN_COUNT"	NUMBER(7)		NOT NULL,	/* 상품 개수 */
	"ORDER_MAIN_NUM"	NUMBER		NOT NULL,		/* 주문번호 */
	
	CONSTRAINT ORDER_DETAIL_PK PRIMARY KEY (ORDER_DETAIL_NUM),
	CONSTRAINT ORDER_DETAIL_FK FOREIGN KEY (ORDER_MAIN_NUM) REFERENCES ORDER_MAIN (ORDER_MAIN_NUM)
);

CREATE SEQUENCE ORDER_MAIN_SEQ;
CREATE SEQUENCE ORDER_DETAIL_SEQ;