CREATE TABLE "MEMBER" (
	"MEM_NUM"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(12)	UNIQUE	NOT NULL,
	"MEM_AUTH"	NUMBER(1)	DEFAULT 2	NOT NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY (MEM_NUM)
);

CREATE TABLE "MEMBER_DETAIL" (
	"MEM_NUM"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(12)		NOT NULL,
	"MEM_PW"	VARCHAR2(20)		NOT NULL,
	"MEM_NAME"	VARCHAR2(30)		NOT NULL,
	"MEM_PHONE"	VARCHAR2(15)		NOT NULL,
	"MEM_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEM_PHOTO" VARCHAR2(150)		NOT NULL,
	"MEM_ZIPCODE"	VARCHAR2(5)		NULL,
	"MEM_ADDRESS1"	VARCHAR2(50)		NULL,
	"MEM_ADDRESS2"	VARCHAR2(50)		NULL,
	"MEM_REG"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEM_MODIFY"	DATE		NULL,
	CONSTRAINT MEMBER_DETAIL_PK PRIMARY KEY (MEM_NUM),
	CONSTRAINT MEMBER_DETAIL_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBER (MEM_NUM)
);


CREATE TABLE "PRODUCT" (
	"PRO_NUM"	NUMBER		NOT NULL,
	"PRO_NAME"	VARCHAR2(50)		NOT NULL,
	"PRO_PRICE"	NUMBER(6)		NOT NULL,
	"PRO_PICTURE"	VARCHAR2(500)		NOT NULL,
	"PRO_COUNT"	NUMBER(2)		NOT NULL,
	"PRO_LEVEL"	VARCHAR2(10)		NOT NULL,
	CONSTRAINT PRODUCT_PK PRIMARY KEY (PRO_NUM)
);


CREATE TABLE "CART" (
	"CART_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"PRO_NUM"	NUMBER		NOT NULL,
	"CART_COUNT"	NUMBER(5)		NOT NULL,
	CONSTRAINT CART_PK PRIMARY KEY (CART_NUM),
	CONSTRAINT CART_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBER_DETAIL (MEM_NUM),
	CONSTRAINT CART_FK FOREIGN KEY (PRO_NUM) REFERENCES PRODUCT (PRO_NUM)
);

CREATE TABLE "ORDER" (
	"ORDER_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"ORDER_NAME"	VARCHAR2(600)		NOT NULL,
	"ORDER_TOTAL"	NUMBER(7)		NOT NULL,
	"PAYMENT"	NUMBER(1)		NOT NULL,
	"ORDER_DATE"	DATE		NOT NULL,
	"STATUS"	NUMBER(1)	DEFAULT 0	NOT NULL,
	"MEM_ZIPCODE"	VARCHAR2(5)		NOT NULL,
	"MEM_ADDRESS1"	VARCHAR2(50)		NOT NULL,
	"MEM_ADDRESS2"	VARCHAR2(50)		NOT NULL,
	"MEM_PHONE"	VARCHAR2(15)		NOT NULL,
	CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_NUM),
	CONSTRAINT ORDER_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBER_DETAIL (MEM_NUM)
);

CREATE TABLE "ORDER_DETAIL" (
	"ORDER_DETAIL_NUM"	NUMBER		NOT NULL,
	"OREDER_NUM"	NUMBER		NOT NULL,
	"PRO_NAME"	VARCHAR2(50)		NOT NULL,
	"PRO_PRICE"	NUMBER(8)		NOT NULL,
	"PRO_TOTAL"	NUMBER(8)		NOT NULL,
	"PRO_COUNT"	NUMBER(7)		NOT NULL,
	CONSTRAINT ORDER_DETAIL_PK PRIMARY KEY (ORDER_DETAIL_NUM),
	CONSTRAINT ORDER_DETAIL_FK FOREIGN KEY (ORDER_NUM) REFERENCES ORDER (ORDER_NUM)
);

CREATE TABLE "RESERVE" (
	"RES_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"RES_DATE"	VARCHAR2(10)		NOT NULL,
	"RES_TIME"	VARCHAR2(8)		NOT NULL,
	"RES_COUNT"	NUMBER(2)		NOT NULL,
	"ROOM_NUM"	NUMBER		NOT NULL,
	CONSTRAINT RESERVE_PK PRIMARY KEY (RES_NUM),
	CONSTRAINT RESERVE_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBER_DETAIL (MEM_NUM),
	CONSTRAINT RESERVE_FK FOREIGN KEY (ROOM_NUM) REFERENCES ROOM (ROOM_NUM)
);


CREATE TABLE "ROOM" (
	"ROOM_NUM"	NUMBER		NOT NULL,
	"ROOM_SIZE"	NUMBER(2)		NOT NULL,
	"ROOM_DETAIL"	VARCHAR2(150)		NOT NULL,
	"ROOM_NAME"	VARCHAR2(30)		NOT NULL,
	CONSTRAINT ROOM_PK PRIMARY KEY (ROOM_NUM)
);


CREATE TABLE "REVIEW" (
	"REV_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"PRO_NUM"	NUMBER		NOT NULL,
	"REV_CONTENT"	VARCHAR2(50)		NOT NULL,
	"REV_STAR"	NUMBER(1)		NOT NULL,
	"REV_DATE"	DATE		NOT NULL,
	CONSTRAINT REVIEW_PK PRIMARY KEY (REV_NUM),
	CONSTRAINT REVIEW_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBER_DETAIL (MEM_NUM),
	CONSTRAINT REVIEW_FK FOREIGN KEY (PRO_NUM) REFERENCES PRODUCT (PRO_NUM)
);


CREATE TABLE "NOTICE" (
	"NOTI_NUM"	NUMBER		NOT NULL,
	"NOTI_TITLE"	VARCHAR2(20)		NOT NULL,
	"NOTI_CONTENT"	CLOB		NOT NULL,
	"NOTI_PHOTO"	VARCHAR2(50)		NULL,
	"NOTI_DATE"	DATE		NOT NULL,
	CONSTRAINT NOTICE_PK PRIMARY KEY (NOTI_NUM)
);


CREATE TABLE "INQUIRY" (
	"INQU_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"INQU_TITLE"	VARCHAR2(20)		NOT NULL,
	"INQU_CONTENT"	CLOB		NOT NULL,
	"INQU_FILE"	VARCHAR2(50)		NULL,
	"INQU_DATE"	DATE		NOT NULL,
	"INQU_CHECK"	NUMBER(1)		NOT NULL,
	CONSTRAINT INQUIRY_PK PRIMARY KEY (INQU_NUM),
	CONSTRAINT INQUIRY_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBER_DETAIL (MEM_NUM)
);


CREATE TABLE "INQUIRY_RPL" (
	"INQU_RPL_NUM"	NUMBER		NOT NULL,
	"INQU_NUM"	NUMBER		NOT NULL,
	"INQU_RPL_COTENT"	VARCHAR2(50)		NOT NULL,
	"INQU_RPL_DATE"	DATE		NOT NULL,
	CONSTRAINT INQUIRY_RPL_PK PRIMARY KEY (INQU_RPL_NUM),
	CONSTRAINT INQUIRY_RPL_FK FOREIGN KEY (INQU_NUM) REFERENCES INQUIRY (INQU_NUM)
);

CREATE SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_DETAIL_SEQ;
CREATE SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE CART_SEQ;
CREATE SEQUENCE ORDER_SEQ;
CREATE SEQUENCE ORDER_DETAIL_SEQ;
CREATE SEQUENCE RESERVE_SEQ;
CREATE SEQUENCE ROOM_SEQ;
CREATE SEQUENCE REVIEW_SEQ;
CREATE SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE INQUIRY_SEQ;
CREATE SEQUENCE INQUIRY_RPL_SEQ;
